### ISSUE TITLE
旋转90°/270°花屏，180°没问题

### ISSUE THREAD

**Issue by huagengithub** [Yangandmore/yuv-tool#1]
我把Android摄像头拿到的yuv数据旋转处理后再写入视频文件（宽高不等），遇到了如题所示的问题。

~_~ 非常感谢作者的分享，代码很好用。

**Comment by Yangandmore** [comment]
> 我把Android摄像头的yuv数据转过来处理后面的视频文件（宽高不等），遇到了如题所示的问题。
> 
> ~_~ 非常感谢作者的分享，代码很好用。

请问下，这边单个yuv文件有没有遇到过90/270花屏的现象，或者方便的话吧yuv文件发我，我这边看看

**Comment by huagengithub** [comment]
@Yangandmore  
感谢回复，我保存了一份数据（即下面代码中的data.data），请看[https://www.drivehq.com/file/DFPublishFile.aspx/FileID8198736050/Keyi6wwdtb8427m/temp_1624535510551.YUV](yuv文件)

我的调用代码，其中data.data是直接从摄像头获取的数据，预览的size是800*600，希望转成600*800
 byte[] i420Data = LibYUVUtil.NV21ToI420(data.data, size.width, size.height);
                                 i420Data = LibYUVUtil.I420Rotate(i420Data,size.width, size.height, rotation);
                                 data.data =  LibYUVUtil.I420ToNV21(i420Data ,size.width, size.height);

**Comment by huagengithub** [comment]
@Yangandmore 
刚才那个文件链接失效了，这是新的：
[https://www.drivehq.com/file/DFPublishFile.aspx/FileID8198824503/Keycrwc7cwxs2tn/temp_1624535510551.YUV](url)

**Comment by Yangandmore** [comment]
> @Yangandmore
> 刚才那个文件链接失效了，这是新的：
> [https://www.drivehq.com/file/DFPublishFile.aspx/FileID8198824503/Keycrwc7cwxs2tn/temp_1624535510551.YUV](url)

我这边测试了一个，项目里面的assets里有相应的文件 640*360。
大概发现了问题，就是在I420转NV21的时候，传入的宽高值有点问题，以640*360为例：
byte[] i420Data = LibYUVUtil.NV21ToI420(data.data, size.width, size.height);  640， 360
i420Data = LibYUVUtil.I420Rotate(i420Data,size.width, size.height, rotation);640，360
data.data = LibYUVUtil.I420ToNV21(i420Data ,size.width, size.height);640，360，而不是360，640
问题就在最后一个

**Comment by Yangandmore** [comment]
> @Yangandmore
> 刚才那个文件链接失效了，这是新的：
> [https://www.drivehq.com/file/DFPublishFile.aspx/FileID8198824503/Keycrwc7cwxs2tn/temp_1624535510551.YUV](url)

当然，在

**Comment by Yangandmore** [comment]
> > @Yangandmore
> > 刚才那个文件链接失效了，这是新的：
> > [https://www.drivehq.com/file/DFPublishFile.aspx/FileID8198824503/Keycrwc7cwxs2tn/temp_1624535510551.YUV](url)
> 
> 我这边测试了一个，项目里面的assets里有相应的文件 640_360。 大概发现了问题，就是在I420转NV21的时候，传入的宽高值有点问题，以640_360为例：
> byte[] i420Data = LibYUVUtil.NV21ToI420(data.data, size.width, size.height); 640， 360
> i420Data = LibYUVUtil.I420Rotate(i420Data,size.width, size.height, rotation);640，360
> data.data = LibYUVUtil.I420ToNV21(i420Data ,size.width, size.height);640，360，而不是360，640
> 问题就在最后一个

这里，最后的640，360，无论是哪个方式，我都试过了，没有任何问题，你可以先拿这个文件调试一下，就在这个项目demo下调试即可。整个流程没有任何问题，每张转换的图片我都看过，如果需要分步骤调试，建议将每张转换后，用yuv图片工具看一下是否有问题，再进行下一步运行。

**Comment by huagengithub** [comment]
@Yangandmore 
我有在自己的项目里测试，旋转确实没问题，问题出在我把图片翻转后通过FFmpeg生成video时，FFmpeg处没有调整生成video的宽高，这也是为什么旋转180°没问题。
感谢您的帮助，浪费您时间了^V^
