### ISSUE TITLE
添加 crop 支持

### ISSUE THREAD

**Issue by tiann** [Yangandmore/yuv-tool#2]

**Comment by Yangandmore** [comment]
我这边来添加该功能，如果需要该功能的实例代码可以参考如下链接：
[https://yangandmore.github.io/2019/03/07/libYUV%E7%BC%96%E8%AF%91/](url)

**Comment by Yangandmore** [comment]
@tiann 后面添加该功能，如果需要示例代码，可以看这里[https://yangandmore.github.io/2019/03/07/libYUV%E7%BC%96%E8%AF%91/](url)

**Comment by Yangandmore** [comment]
@tiann 增加了对I420和argb的裁剪功能
